name: Check CloudApp

on:
  pull_request:
    branches: ["main"]
    paths:
      [
        "package.json",
        "package-lock.json",
        "tsconfig.override.json",
        "cloudapp/src/**",
        ".github/workflows/**",
      ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Audit dependencies (fail on critical)
        run: npm audit --audit-level=critical

      - name: Build CloudApp ('eca build')
        run: |
          npm ci
          npm i -g @exlibris/exl-cloudapp-cli
          eca build | grep 'Generated'
